DROP TABLE IF EXISTS user
CREATE TABLE user(id BIGINT(20) PRIMARY KEY AUTO_INCREMENT, account_id VARCHAR(20) NOT NULL, user_nm VARCHAR(30) NOT NULL, enabled BIT(1)	NOT NULL)
DROP TABLE IF EXISTS item
CREATE TABLE item(id BIGINT(20) PRIMARY KEY AUTO_INCREMENT, item_group VARCHAR(5) NOT NULL, item_nm VARCHAR(30) NOT NULL, item_price INT(10) NOT NULL, item_description TEXT NULL, enabled BIT(1)	NOT NULL)
DROP TABLE IF EXISTS buy
create table buy(id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY key, user_id BIGINT(20) NOT NULL, item_id BIGINT(20) NOT NULL)
DROP TABLE IF EXISTS save
CREATE TABLE save (id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY key, user_id BIGINT(20) NOT NULL,item_id BIGINT(20) NOT NULL,item_price INT(10) NOT NULL)
DROP TABLE IF EXISTS member
CREATE TABLE member(id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY key, passwoed VARCHAR(50) NOT NULL,user_name VARCHAR(30) NOT NULL,phone_num VARCHAR(50) NOT NULL,create_date TIMESTAMP NOT NULL)