DROP TABLE IF EXISTS user
CREATE TABLE user(seq BIGINT(20) PRIMARY KEY AUTO_INCREMENT, user_id VARCHAR(20) NOT NULL, user_nm VARCHAR(30) NOT NULL, enabled BIT(1)	NOT NULL)
DROP TABLE IF EXISTS item
CREATE TABLE item(seq BIGINT(20) PRIMARY KEY AUTO_INCREMENT, item_group VARCHAR(5) NOT NULL, item_nm VARCHAR(30) NOT NULL, item_price INT(10) NOT NULL, item_description TEXT NULL, enabled BIT(1)	NOT NULL)
DROP TABLE IF EXISTS buy
create table buy(seq BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY key, user_seq BIGINT(20) NOT NULL, item_seq BIGINT(20) NOT NULL)